version: 2.1

jobs:
    build-live:
        docker:
            - image: jekyll/jekyll:latest
        steps:
            - run:
                name: dependencies-live
                command: |
                    apk update;
                    apk add rsync openssh-client

            - checkout

            - run:
                name: build-live
                command: |
                    chmod -R 777 ~/
                    jekyll build

            - run:
                name: deploy-live
                command: |
                    rsync -avz --delete -e 'ssh -p 53122 -o StrictHostKeyChecking=no' --omit-dir-times --exclude='.git/' --exclude='.gitignore' --exclude='.circleci/' _site/. circleci@${SERVER_NAME}:${PROD_PATH};

    build-staging:
        docker:
            - image: jekyll/jekyll:latest
              environment:
                SERVER_DOMAIN: $SERVER_NAME
                SERVER_PATH: $STAGING_PATH
                SERVER_PORT: $SSH_PORT
        steps:
            - run:
                name: dependencies-staging
                command: |
                    apk update;
                    apk add rsync openssh-client

            - checkout

            - run:
                name: build-staging
                command: |
                    chmod -R 777 ~/
                    jekyll build --drafts

            - run:
                name: deploy-staging
                command: |
                    rsync -avz --delete -e 'ssh -p $SERVER_PORT -o StrictHostKeyChecking=no' --omit-dir-times --exclude='.git/' --exclude='.gitignore' --exclude='.circleci/' _site/. circleci@$SERVER_DOMAIN:$SERVER_PATH;

 

workflows:
    do-build:
        jobs:
            - build-live:
                filters:
                    branches:
                        only: 
                            - main
            - build-staging:
                filters:
                    branches:
                        only:
                            - main
                            - staging

