version: 2.1

jobs:
    build-live:
        docker:
            - image: ubuntu
        steps:
            - run:
                name: build-dependencies
                command: |
                    apt update;
                    apt install -y git rsync;
        
            - checkout

            - add_ssh_keys:
                fingerprints:
                    - "3b:0e:79:7c:c2:3c:2d:d5:db:b4:85:b7:05:0c:ad:d1"

            - run:
                name: build-deploy
                command: |
                    ssh -p 53122 circleci@lon3.dustyservers.com
                    rsync -avz --delete -e 'ssh -p 53122 -o StrictHostKeyChecking=no' --omit-dir-times --chmod=0644 --exclude='.gitignore' --exclude='.circleci/' . circleci@lon3.dustyservers.com:/var/www/staging.henrycole.uk/html/;

workflows:
    do-build:
        jobs:
            - build-live

