version: 2.1

jobs:
    build-live:
        docker:
            - image: jekyll/jekyll:latest
        steps:
            - run:
                name: dependencies-live
                command: |
                    apk update;
                    apk add rsync openssh-client

            - checkout

            - run:
                name: build-live
                command: |
                    chmod -R 777 ~/
                    jekyll build

            - run:
                name: deploy-live
                command: |
                    rsync -avz --delete -e 'ssh -p 53122 -o StrictHostKeyChecking=no' --omit-dir-times --exclude='.git/' --exclude='.gitignore' --exclude='.circleci/' _site/. circleci@lon3.dustyservers.com:/var/www/henrycole.uk/html/;

    build-staging:
        docker:
            - image: jekyll/jekyll:latest
        steps:
            - run:
                name: dependencies-staging
                command: |
                    apk update;
                    apk add rsync openssh-client

            - checkout

            - run:
                name: build-staging
                command: |
                    chmod -R 777 ~/
                    jekyll build --drafts

            - run:
                name: deploy-staging
                command: |
                    rsync -avz --delete -e 'ssh -p 53122 -o StrictHostKeyChecking=no' --omit-dir-times --exclude='.git/' --exclude='.gitignore' --exclude='.circleci/' _site/. circleci@lon3.dustyservers.com:/var/www/staging.henrycole.uk/html/;

 

workflows:
    do-build:
        jobs:
            - build-live:
                filters:
                    branches:
                        only: 
                            - main
            - build-staging:
                filters:
                    branches:
                        only:
                            - staging

