version: 2.1

jobs:
    build-live:
        docker:
            - image: jekyll/jekyll:latest
        steps:
            - run:
                name: dependencies-live
                command: |
                    apk update;
                    apk add rsync openssh-client

            - checkout

            - run:
                name: build-live
                command: |
                    chmod -R 777 ~/
                    jekyll build

            - run:
                name: deploy-live
                command: |
                    rsync -avz --delete -e 'ssh -p 53122 -o StrictHostKeyChecking=no' --omit-dir-times --exclude='.git/' --exclude='.gitignore' --exclude='.circleci/' _site/. circleci@${SERVER_NAME}:${PROD_PATH};

    build-staging:
        parameters:
            server-name:
                type: env_var_name
                default: $SERVER_NAME
            ssh-port:
                type: env_var_name
                default: $SSH_PORT
            server-path:
                type: env_var_name
                default: $STAGING_PATH
        docker:
            - image: jekyll/jekyll:latest
        steps:
            - run:
                name: dependencies-staging
                command: |
                    apk update;
                    apk add rsync openssh-client

            - checkout

            - run:
                name: build-staging
                command: |
                    chmod -R 777 ~/
                    jekyll build --drafts

            - run:
                name: deploy-staging
                command: |
                    rsync -avz --delete -e 'ssh -p ${<< parameters.ssh-port >>} -o StrictHostKeyChecking=no' --omit-dir-times --exclude='.git/' --exclude='.gitignore' --exclude='.circleci/' _site/. circleci@${<< parameters.server-name >>}:${<< parameters.server-path >>};

 

workflows:
    do-build:
        jobs:
            - build-live:
                filters:
                    branches:
                        only: 
                            - main
            - build-staging:
                filters:
                    branches:
                        only:
                            - main
                            - staging

